<a href="https://colab.research.google.com/github/Codegea/AplicacionesHibridas/blob/master/TransfAnalisBasicPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Lectura de una archivo .xlsl

In [14]:
import pandas as pd # 1. importamos la libreria de pandas.

In [15]:
from google.colab import files # 2. Para subir el archivo desd la PC.
uploaded = files.upload()

df = pd.read_excel('excel_actividad.xlsx', sheet_name='Datos_Crudos') # 3. Le decimos exactamente cual hoja del .xlsx queremos que lea

Saving excel_actividad.xlsx to excel_actividad (7).xlsx

In [19]:
df.head() # 4. Lee todo el archivo y muestra los primero 5 registros

,id_estudiante,nombre_estudiante,programa,asignatura,grupo,tipo_actividad,fecha_entrega_raw,horas_estudio_raw,modalidad_entrega_raw,nota_quiz,nota_taller,meta_horas,asistencia_pct
0,EST001,Ana Torres,Ingeniería de Datos,Programación,C,Proyecto,13/04/26,5h,presencial,4.2,4.1,6,88
1,EST002,Luis Pérez,Psicología,Programación,A,Taller,13/04/26,5h,remota,3.8,3.8,12,77
2,EST003,María Gómez,Psicología,Visualización de Datos,B,Taller,12-04-2026,ocho,Híbrida,2.8,2.9,10,73
3,EST004,Carlos Rojas,Ingeniería de Datos,Metodología,A,Proyecto,15-04-26,dos horas,hibrida,4.4,4.3,6,99
4,EST005,Laura Martínez,Psicología,Programación,C,Proyecto,19/04/26,7,Presencial,4.1,2.4,8,94

In [20]:
df.shape # 5. Nos dice cuantas filas y columnas tiene nuestro archivo

(36, 13)

In [21]:
list(df.columns) # 6.Lista el nombre de las columnas
df.dtypes # 7. Muestra los tipos de datos

id_estudiante             object
nombre_estudiante         object
programa                  object
asignatura                object
grupo                     object
tipo_actividad            object
fecha_entrega_raw         object
horas_estudio_raw         object
modalidad_entrega_raw     object
nota_quiz                float64
nota_taller              float64
meta_horas                 int64
asistencia_pct             int64
dtype: object